name: agixtsdk
description: "An SDK for AGiXT"
version: 0.0.1
homepage: https://agixt.com

environment:
    sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  uuid: ^4.5.1
  path: ^1.9.0
  async: ^2.13.0
  crypto: ^3.0.6
  fake_async: ^1.3.3
  fixnum: ^1.1.1
  http_parser: ^4.1.2
  leak_tracker: ^10.0.9
  typed_data: ^1.4.0
  web: ^1.1.0
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
